"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Testing(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IS_EARLY_REPLY_FIELD_NUMBER: builtins.int
    IS_EARLY_EXIT_FIELD_NUMBER: builtins.int
    TEST_STORES_FIELD_NUMBER: builtins.int
    is_early_reply: builtins.bool
    is_early_exit: builtins.bool
    test_stores: builtins.bool
    def __init__(
        self,
        *,
        is_early_reply: builtins.bool = ...,
        is_early_exit: builtins.bool = ...,
        test_stores: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["is_early_exit", b"is_early_exit", "is_early_reply", b"is_early_reply", "test_stores", b"test_stores"]) -> None: ...

global___Testing = Testing

@typing_extensions.final
class TestingResults(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TEST_STORES_SUCCESS_FIELD_NUMBER: builtins.int
    test_stores_success: builtins.bool
    def __init__(
        self,
        *,
        test_stores_success: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["test_stores_success", b"test_stores_success"]) -> None: ...

global___TestingResults = TestingResults

@typing_extensions.final
class Request(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    TESTING_FIELD_NUMBER: builtins.int
    name: builtins.str
    @property
    def testing(self) -> global___Testing: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        testing: global___Testing | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["testing", b"testing"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name", "testing", b"testing"]) -> None: ...

global___Request = Request

@typing_extensions.final
class NodeBRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GREETING_FIELD_NUMBER: builtins.int
    TESTING_FIELD_NUMBER: builtins.int
    TESTING_RESULTS_FIELD_NUMBER: builtins.int
    greeting: builtins.str
    @property
    def testing(self) -> global___Testing: ...
    @property
    def testing_results(self) -> global___TestingResults: ...
    def __init__(
        self,
        *,
        greeting: builtins.str = ...,
        testing: global___Testing | None = ...,
        testing_results: global___TestingResults | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["testing", b"testing", "testing_results", b"testing_results"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["greeting", b"greeting", "testing", b"testing", "testing_results", b"testing_results"]) -> None: ...

global___NodeBRequest = NodeBRequest

@typing_extensions.final
class NodeCRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GREETING_FIELD_NUMBER: builtins.int
    TESTING_FIELD_NUMBER: builtins.int
    TESTING_RESULTS_FIELD_NUMBER: builtins.int
    greeting: builtins.str
    @property
    def testing(self) -> global___Testing: ...
    @property
    def testing_results(self) -> global___TestingResults: ...
    def __init__(
        self,
        *,
        greeting: builtins.str = ...,
        testing: global___Testing | None = ...,
        testing_results: global___TestingResults | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["testing", b"testing", "testing_results", b"testing_results"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["greeting", b"greeting", "testing", b"testing", "testing_results", b"testing_results"]) -> None: ...

global___NodeCRequest = NodeCRequest

@typing_extensions.final
class Response(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GREETING_FIELD_NUMBER: builtins.int
    TESTING_FIELD_NUMBER: builtins.int
    TESTING_RESULTS_FIELD_NUMBER: builtins.int
    greeting: builtins.str
    @property
    def testing(self) -> global___Testing: ...
    @property
    def testing_results(self) -> global___TestingResults: ...
    def __init__(
        self,
        *,
        greeting: builtins.str = ...,
        testing: global___Testing | None = ...,
        testing_results: global___TestingResults | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["testing", b"testing", "testing_results", b"testing_results"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["greeting", b"greeting", "testing", b"testing", "testing_results", b"testing_results"]) -> None: ...

global___Response = Response
