# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_msg.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test_msg.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\003kre',
  serialized_pb=b'\n\x0etest_msg.proto\"\x19\n\tTestInput\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1e\n\nTestOutput\x12\x10\n\x08greeting\x18\x01 \x01(\tB\x05Z\x03kreb\x06proto3'
)




_TESTINPUT = _descriptor.Descriptor(
  name='TestInput',
  full_name='TestInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='TestInput.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=43,
)


_TESTOUTPUT = _descriptor.Descriptor(
  name='TestOutput',
  full_name='TestOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='greeting', full_name='TestOutput.greeting', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['TestInput'] = _TESTINPUT
DESCRIPTOR.message_types_by_name['TestOutput'] = _TESTOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestInput = _reflection.GeneratedProtocolMessageType('TestInput', (_message.Message,), {
  'DESCRIPTOR' : _TESTINPUT,
  '__module__' : 'test_msg_pb2'
  # @@protoc_insertion_point(class_scope:TestInput)
  })
_sym_db.RegisterMessage(TestInput)

TestOutput = _reflection.GeneratedProtocolMessageType('TestOutput', (_message.Message,), {
  'DESCRIPTOR' : _TESTOUTPUT,
  '__module__' : 'test_msg_pb2'
  # @@protoc_insertion_point(class_scope:TestOutput)
  })
_sym_db.RegisterMessage(TestOutput)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
