// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: public_input.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EntrypointClient is the client API for Entrypoint service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EntrypointClient interface {
	Greet(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type entrypointClient struct {
	cc grpc.ClientConnInterface
}

func NewEntrypointClient(cc grpc.ClientConnInterface) EntrypointClient {
	return &entrypointClient{cc}
}

func (c *entrypointClient) Greet(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/main.Entrypoint/Greet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EntrypointServer is the server API for Entrypoint service.
// All implementations must embed UnimplementedEntrypointServer
// for forward compatibility
type EntrypointServer interface {
	Greet(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedEntrypointServer()
}

// UnimplementedEntrypointServer must be embedded to have forward compatible implementations.
type UnimplementedEntrypointServer struct {
}

func (UnimplementedEntrypointServer) Greet(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greet not implemented")
}
func (UnimplementedEntrypointServer) mustEmbedUnimplementedEntrypointServer() {}

// UnsafeEntrypointServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EntrypointServer will
// result in compilation errors.
type UnsafeEntrypointServer interface {
	mustEmbedUnimplementedEntrypointServer()
}

func RegisterEntrypointServer(s grpc.ServiceRegistrar, srv EntrypointServer) {
	s.RegisterService(&Entrypoint_ServiceDesc, srv)
}

func _Entrypoint_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntrypointServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Entrypoint/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntrypointServer).Greet(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Entrypoint_ServiceDesc is the grpc.ServiceDesc for Entrypoint service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Entrypoint_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.Entrypoint",
	HandlerType: (*EntrypointServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _Entrypoint_Greet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "public_input.proto",
}
