version: "3"
services:

  mongo:
    image: "mongo:5.0.8"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=admin
    ports:
      - "27017:27017"
    logging:
      driver: none

  influx:
    image: "influxdb:1.8-alpine"
    ports:
      - "8086:8086"
    environment:
      "INFLUXDB_DB": "runtime1"
      "INFLUXDB_META_DIR": "/var/lib/influxdb/meta2"
    logging:
          driver: none 

  nats:
    image: "nats:2.8.1"
    command:
      - "-js"
      - "--config"
      - "/etc/nats/nats.conf"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - "./config:/etc/nats"

  nats_init:
    build:
      context: "nats_init"
      dockerfile: "./Dockerfile"
    env_file:
      - env/.env.common
      - env/.env.nats
    depends_on:
      - nats
  node-a-py:
    build:
      context: "../../kre-py"
      dockerfile: "./Dockerfile"
    volumes:
      - "./nodeA-vol:/tmp"
    env_file:
      - env/.env.common
      - env/.env.nodeA
    depends_on:
      - nats_init
    logging:
          driver: none 

  node-b-py:
    build:
      context: "../../kre-py"
      dockerfile: "./Dockerfile"
    volumes:
      - "./nodeB-vol:/tmp"
    env_file:
      - env/.env.common
      - env/.env.nodeB
    depends_on:
      - nats_init
    logging:
          driver: none 

  node-c-go:
    build:
      context: "../../kre-go"
      dockerfile: "./Dockerfile"
    volumes:
      - "./nodeC-vol:/tmp"
    env_file:
      - env/.env.common
      - env/.env.nodeC
    depends_on:
      - nats_init
    logging:
          driver: none 

  exitpoint:
    build:
      context: "../../kre-go"
      dockerfile: "./Dockerfile"
    volumes:
      - "./exitpoint-vol:/tmp"
    env_file:
      - env/.env.common
      - env/.env.exitpoint
    depends_on:
      - nats_init
    logging:
          driver: none      

  node-entrypoint:
    build:
      context: "../../kre-entrypoint"
      dockerfile: "./Dockerfile"
    volumes:
      - "./entrypoint-vol/src:/src"
      - "./entrypoint-vol/krt-files:/krt-files"
    ports:
      - "9000:9000"
    env_file:
      - env/.env.common
      - env/.env.entrypoint
    depends_on:
      - nats_init
