version: "3"
services:
  nats:
    image: "nats:2.1.6"
    ports:
      - "4222:4222"
      - "8222:8222"
  mongo:
    image: "mongo:4.2"
    ports:
      - "27017:27017"
  influx:
    image: "influxdb:1.7-alpine"
    ports:
      - "8088:8088"
