version: "3"
services:
  nats:
    image: "nats:2.8.4"
    command:
      - "-js"
    ports:
      - "4222:4222"
      - "8222:8222"
  mongo:
    image: "mongo:4.2"
    ports:
      - "27017:27017"
  influx:
    image: "influxdb:1.8-alpine"
    ports:
      - 8086:8086
  influx_init:
    image: "influxdb:1.8-alpine"
    environment:
      INFLUX_DATABASE: "kre"
    volumes: 
      - "./influx:/docker-entrypoint-initdb.d"
    command: /init-influxdb.sh
