# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public_input.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12public_input.proto\x12\x04main\"\x17\n\x07Request\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\x0cNodeBRequest\x12\x10\n\x08greeting\x18\x01 \x01(\t\" \n\x0cNodeCRequest\x12\x10\n\x08greeting\x18\x01 \x01(\t\"\x1c\n\x08Response\x12\x10\n\x08greeting\x18\x01 \x01(\t26\n\nEntrypoint\x12(\n\x05Greet\x12\r.main.Request\x1a\x0e.main.Response\"\x00\x42\tZ\x07./protob\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_NODEBREQUEST = DESCRIPTOR.message_types_by_name['NodeBRequest']
_NODECREQUEST = DESCRIPTOR.message_types_by_name['NodeCRequest']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'public_input_pb2'
  # @@protoc_insertion_point(class_scope:main.Request)
  })
_sym_db.RegisterMessage(Request)

NodeBRequest = _reflection.GeneratedProtocolMessageType('NodeBRequest', (_message.Message,), {
  'DESCRIPTOR' : _NODEBREQUEST,
  '__module__' : 'public_input_pb2'
  # @@protoc_insertion_point(class_scope:main.NodeBRequest)
  })
_sym_db.RegisterMessage(NodeBRequest)

NodeCRequest = _reflection.GeneratedProtocolMessageType('NodeCRequest', (_message.Message,), {
  'DESCRIPTOR' : _NODECREQUEST,
  '__module__' : 'public_input_pb2'
  # @@protoc_insertion_point(class_scope:main.NodeCRequest)
  })
_sym_db.RegisterMessage(NodeCRequest)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'public_input_pb2'
  # @@protoc_insertion_point(class_scope:main.Response)
  })
_sym_db.RegisterMessage(Response)

_ENTRYPOINT = DESCRIPTOR.services_by_name['Entrypoint']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007./proto'
  _REQUEST._serialized_start=28
  _REQUEST._serialized_end=51
  _NODEBREQUEST._serialized_start=53
  _NODEBREQUEST._serialized_end=85
  _NODECREQUEST._serialized_start=87
  _NODECREQUEST._serialized_end=119
  _RESPONSE._serialized_start=121
  _RESPONSE._serialized_end=149
  _ENTRYPOINT._serialized_start=151
  _ENTRYPOINT._serialized_end=205
# @@protoc_insertion_point(module_scope)
