// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kre_nats_msg.proto

package kre

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KreNatsMessage struct {
	TrackingId           string                     `protobuf:"bytes,1,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	Tracking             []*KreNatsMessage_Tracking `protobuf:"bytes,2,rep,name=tracking,proto3" json:"tracking,omitempty"`
	Reply                string                     `protobuf:"bytes,3,opt,name=reply,proto3" json:"reply,omitempty"`
	Payload              *any.Any                   `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Error                string                     `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *KreNatsMessage) Reset()         { *m = KreNatsMessage{} }
func (m *KreNatsMessage) String() string { return proto.CompactTextString(m) }
func (*KreNatsMessage) ProtoMessage()    {}
func (*KreNatsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_300f81baeeb7bcc5, []int{0}
}

func (m *KreNatsMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KreNatsMessage.Unmarshal(m, b)
}
func (m *KreNatsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KreNatsMessage.Marshal(b, m, deterministic)
}
func (m *KreNatsMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KreNatsMessage.Merge(m, src)
}
func (m *KreNatsMessage) XXX_Size() int {
	return xxx_messageInfo_KreNatsMessage.Size(m)
}
func (m *KreNatsMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_KreNatsMessage.DiscardUnknown(m)
}

var xxx_messageInfo_KreNatsMessage proto.InternalMessageInfo

func (m *KreNatsMessage) GetTrackingId() string {
	if m != nil {
		return m.TrackingId
	}
	return ""
}

func (m *KreNatsMessage) GetTracking() []*KreNatsMessage_Tracking {
	if m != nil {
		return m.Tracking
	}
	return nil
}

func (m *KreNatsMessage) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func (m *KreNatsMessage) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *KreNatsMessage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type KreNatsMessage_Tracking struct {
	NodeName             string   `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Start                string   `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End                  string   `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KreNatsMessage_Tracking) Reset()         { *m = KreNatsMessage_Tracking{} }
func (m *KreNatsMessage_Tracking) String() string { return proto.CompactTextString(m) }
func (*KreNatsMessage_Tracking) ProtoMessage()    {}
func (*KreNatsMessage_Tracking) Descriptor() ([]byte, []int) {
	return fileDescriptor_300f81baeeb7bcc5, []int{0, 0}
}

func (m *KreNatsMessage_Tracking) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KreNatsMessage_Tracking.Unmarshal(m, b)
}
func (m *KreNatsMessage_Tracking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KreNatsMessage_Tracking.Marshal(b, m, deterministic)
}
func (m *KreNatsMessage_Tracking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KreNatsMessage_Tracking.Merge(m, src)
}
func (m *KreNatsMessage_Tracking) XXX_Size() int {
	return xxx_messageInfo_KreNatsMessage_Tracking.Size(m)
}
func (m *KreNatsMessage_Tracking) XXX_DiscardUnknown() {
	xxx_messageInfo_KreNatsMessage_Tracking.DiscardUnknown(m)
}

var xxx_messageInfo_KreNatsMessage_Tracking proto.InternalMessageInfo

func (m *KreNatsMessage_Tracking) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *KreNatsMessage_Tracking) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *KreNatsMessage_Tracking) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

func init() {
	proto.RegisterType((*KreNatsMessage)(nil), "KreNatsMessage")
	proto.RegisterType((*KreNatsMessage_Tracking)(nil), "KreNatsMessage.Tracking")
}

func init() {
	proto.RegisterFile("kre_nats_msg.proto", fileDescriptor_300f81baeeb7bcc5)
}

var fileDescriptor_300f81baeeb7bcc5 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x90, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0x87, 0x69, 0xd7, 0xea, 0x76, 0x16, 0x44, 0x42, 0x0f, 0xb1, 0x1e, 0x2c, 0x9e, 0x7a, 0x4a,
	0xa1, 0xfa, 0x02, 0x7a, 0x13, 0xb1, 0xc2, 0xe2, 0xc9, 0xcb, 0x92, 0x9a, 0x31, 0x94, 0x6e, 0x93,
	0x65, 0x12, 0x0f, 0xfb, 0x1e, 0x3e, 0xb0, 0x49, 0x76, 0x23, 0x78, 0xcb, 0x37, 0x7f, 0x7e, 0xf9,
	0x18, 0x60, 0x47, 0xc2, 0xc6, 0x48, 0xef, 0x9a, 0x93, 0xd3, 0xa2, 0x23, 0xeb, 0xed, 0xf2, 0x5a,
	0x5b, 0xab, 0x5b, 0xdc, 0x24, 0xda, 0x7f, 0x7f, 0x6d, 0xa4, 0xe9, 0x87, 0xd6, 0xdd, 0xcf, 0x14,
	0x2e, 0x5f, 0x08, 0x77, 0x61, 0xe1, 0x15, 0x9d, 0x93, 0x1a, 0xd9, 0x2d, 0x54, 0x9e, 0xe4, 0xe7,
	0xf1, 0x60, 0x74, 0x73, 0x50, 0x7c, 0xb2, 0x9a, 0xac, 0xe7, 0x35, 0xe4, 0xd2, 0xb3, 0x62, 0x0f,
	0x50, 0x66, 0xe2, 0xd3, 0x55, 0xb1, 0xae, 0xb6, 0x5c, 0xfc, 0xcf, 0x10, 0xef, 0x63, 0xbf, 0xfe,
	0x9b, 0x64, 0x0b, 0x98, 0x11, 0x76, 0x6d, 0xcf, 0x8b, 0x14, 0x38, 0x00, 0x13, 0x70, 0xd1, 0xc9,
	0xbe, 0xb5, 0x52, 0xf1, 0xb3, 0x50, 0xaf, 0xb6, 0x0b, 0x31, 0xc8, 0x8a, 0x2c, 0x2b, 0x1e, 0x4d,
	0x5f, 0xe7, 0xa1, 0x98, 0x82, 0x44, 0x96, 0xf8, 0x6c, 0x48, 0x49, 0xb0, 0x7c, 0x83, 0x32, 0xff,
	0xc8, 0x6e, 0x60, 0x6e, 0xac, 0x8a, 0x37, 0x38, 0xe1, 0x28, 0x5f, 0xc6, 0xc2, 0x2e, 0x70, 0x5c,
	0x77, 0x5e, 0x92, 0x0f, 0xde, 0x69, 0x3d, 0x01, 0xbb, 0x82, 0x02, 0x8d, 0x1a, 0xc5, 0xe2, 0xf3,
	0x69, 0xf6, 0x51, 0x84, 0x3b, 0xee, 0xcf, 0x93, 0xc4, 0xfd, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xce, 0x20, 0x81, 0xc0, 0x55, 0x01, 0x00, 0x00,
}
