// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: test_msg.proto

package kre

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *TestInput) Reset() {
	*x = TestInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestInput) ProtoMessage() {}

func (x *TestInput) ProtoReflect() protoreflect.Message {
	mi := &file_test_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestInput.ProtoReflect.Descriptor instead.
func (*TestInput) Descriptor() ([]byte, []int) {
	return file_test_msg_proto_rawDescGZIP(), []int{0}
}

func (x *TestInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TestOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Greeting string `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
}

func (x *TestOutput) Reset() {
	*x = TestOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestOutput) ProtoMessage() {}

func (x *TestOutput) ProtoReflect() protoreflect.Message {
	mi := &file_test_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestOutput.ProtoReflect.Descriptor instead.
func (*TestOutput) Descriptor() ([]byte, []int) {
	return file_test_msg_proto_rawDescGZIP(), []int{1}
}

func (x *TestOutput) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

var File_test_msg_proto protoreflect.FileDescriptor

var file_test_msg_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x1f, 0x0a, 0x09, 0x54, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x28, 0x0a, 0x0a, 0x54, 0x65, 0x73, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x42, 0x07, 0x5a, 0x05, 0x2e,
	0x2f, 0x6b, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_test_msg_proto_rawDescOnce sync.Once
	file_test_msg_proto_rawDescData = file_test_msg_proto_rawDesc
)

func file_test_msg_proto_rawDescGZIP() []byte {
	file_test_msg_proto_rawDescOnce.Do(func() {
		file_test_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_msg_proto_rawDescData)
	})
	return file_test_msg_proto_rawDescData
}

var file_test_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_test_msg_proto_goTypes = []interface{}{
	(*TestInput)(nil),  // 0: TestInput
	(*TestOutput)(nil), // 1: TestOutput
}
var file_test_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_msg_proto_init() }
func file_test_msg_proto_init() {
	if File_test_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_msg_proto_goTypes,
		DependencyIndexes: file_test_msg_proto_depIdxs,
		MessageInfos:      file_test_msg_proto_msgTypes,
	}.Build()
	File_test_msg_proto = out.File
	file_test_msg_proto_rawDesc = nil
	file_test_msg_proto_goTypes = nil
	file_test_msg_proto_depIdxs = nil
}
