name: kre-entrypoint Release

on:
  workflow_run:
    workflows:
      - "kre-entrypoint Tests"
    branches: [ main ]
    types:
      - completed

jobs:
  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 14

      - name: Install dependencies
        working-directory: ./kre-entrypoint
        run: npm install

      - name: Create empty release_version file
        working-directory: ./kre-entrypoint
        run: touch release_version.txt

      - name: Release
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.PATNAME }}
        working-directory: ./kre-entrypoint
        run: npx semantic-release --debug

      - name: Upload release_version
        uses: actions/upload-artifact@v2
        with:
          name: release_version
          path: kre-entrypoint/release_version.txt

  docker:
    # TODO: use output from previous job adding an if condiction instead one per step
    # https://lannonbr.com/blog/2020-04-16-gh-actions-job-outputs
    name: Docker
    runs-on: ubuntu-latest
    needs: semantic-release
    steps:

      - name: Download release_version
        uses: actions/download-artifact@v2
        with:
          name: release_version
          path: kre-entrypoint

      - name: Read release_version
        id: release_version
        # Set RELEASE_VERSION environment variable
        run: |
          echo "RELEASE_VERSION=$(cat kre-entrypoint/release_version.txt)" >> $GITHUB_ENV
          if [ "$RELEASE_VERSION" = "" ]; then
            echo "::warning::No new version to release."
          fi

      - name: Checkout code
        if: env.RELEASE_VERSION != ''
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        if: env.RELEASE_VERSION != ''
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        if: env.RELEASE_VERSION != ''
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub Registry
        if: env.RELEASE_VERSION != ''
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        if: env.RELEASE_VERSION != ''
        uses: docker/build-push-action@v2
        with:
          context: ./kre-entrypoint
          file: ./kre-entrypoint/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            konstellation/kre-entrypoint:${{ env.RELEASE_VERSION }}
            konstellation/kre-entrypoint:latest
