name: New Release

on:
  workflow_run:
    workflows:
      - "kre-py Tests"
      - "kre-go Tests"
      - "kre-entrypoint Tests"
      - "krt-files-downloader Tests"
    branches: [ main ]
  push:
    paths:
      # kre-exitpoint and kre-py-objstore does not have tests yet
      - "kre-exitpoint/**/*"
      - "kre-py-objstore/**/*"
    branches: [ main ]

jobs:
  new-release:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Install nodejs
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Run semantic release
      run: |
        npm install
        npx multi-semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
